{{- include "buzz.validate" . -}}
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "buzz.serviceAccountName" . }}
  labels:
    {{- include "buzz.labels" . | nindent 4 }}
  {{- if or (eq .Values.objectStorage.backend "azure") .Values.serviceAccount.annotations }}
  annotations:
    {{- if eq .Values.objectStorage.backend "azure" }}
    azure.workload.identity/client-id: {{ .Values.objectStorage.azure.workloadIdentityClientId | quote }}
    {{- end }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
