apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: buzz-health
  namespace: buzz
  annotations:
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/modsecurity-snippet: |
      SecRuleEngine On
      SecRule &REQUEST_HEADERS:X-Azure-FDID "@eq 0" "id:206,phase:1,deny,status:403,log"
      SecRule REQUEST_HEADERS:X-Azure-FDID "!@streq __FRONT_DOOR_ID__" "id:207,phase:1,deny,status:403,log"
      SecRule REQUEST_HEADERS:X-Buzz-Origin-Verify "!@streq __ORIGIN_VERIFICATION_SECRET__" "id:208,phase:1,deny,status:403,log"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - buzz-origin.kiingo.com
      secretName: buzz-origin-tls
  rules:
    - host: chat.kiingo.com
      http:
        paths:
          - path: /_readiness
            pathType: Exact
            backend:
              service:
                name: buzz
                port:
                  name: health
