apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: buzz-runtime
  namespace: buzz
spec:
  provider: azure
  secretObjects:
    - secretName: buzz-runtime
      type: Opaque
      data:
        - objectName: buzz-relay-private-key
          key: BUZZ_RELAY_PRIVATE_KEY
        - objectName: buzz-agent-private-key
          key: BUZZ_PRIVATE_KEY
        - objectName: buzz-agent-public-key
          key: BUZZ_AGENT_PUBLIC_KEY
        - objectName: buzz-relay-owner-pubkey
          key: RELAY_OWNER_PUBKEY
        - objectName: buzz-git-hook-hmac-secret
          key: BUZZ_GIT_HOOK_HMAC_SECRET
        - objectName: buzz-database-url
          key: DATABASE_URL
        - objectName: buzz-postgres-admin-password
          key: POSTGRES_ADMIN_PASSWORD
        - objectName: buzz-database-password
          key: BUZZ_DATABASE_PASSWORD
        - objectName: buzz-postgres-host
          key: POSTGRES_HOST
        - objectName: buzz-redis-password
          key: redis-password
        - objectName: buzz-redis-url
          key: REDIS_URL
        - objectName: buzz-bridge-internal-token
          key: BUZZ_BRIDGE_INTERNAL_TOKEN
  parameters:
    usePodIdentity: "false"
    clientID: __RELAY_IDENTITY_CLIENT_ID__
    keyvaultName: __KEY_VAULT_NAME__
    cloudName: AzurePublicCloud
    tenantId: __TENANT_ID__
    objects: |
      array:
        - |
          objectName: buzz-relay-private-key
          objectType: secret
        - |
          objectName: buzz-agent-private-key
          objectType: secret
        - |
          objectName: buzz-agent-public-key
          objectType: secret
        - |
          objectName: buzz-relay-owner-pubkey
          objectType: secret
        - |
          objectName: buzz-git-hook-hmac-secret
          objectType: secret
        - |
          objectName: buzz-database-url
          objectType: secret
        - |
          objectName: buzz-postgres-admin-password
          objectType: secret
        - |
          objectName: buzz-database-password
          objectType: secret
        - |
          objectName: buzz-postgres-host
          objectType: secret
        - |
          objectName: buzz-redis-password
          objectType: secret
        - |
          objectName: buzz-redis-url
          objectType: secret
        - |
          objectName: buzz-bridge-internal-token
          objectType: secret
